//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published
//  by the Free Software Foundation; either version 2 of the License, or
//  (at your option) version 3.

//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.

//  You should have received a copy of the GNU Lesser General Public License
//  along with this program; if not, write to the
//  Free Software Foundation, Inc.,
//  51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#include "OutputScript_Bash.hpp"

OutputScript_Bash::OutputScript_Bash()
{
    //ctor
}

std::string OutputScript_Bash::GenerateInit(std::string product, std::string version)
{
    return "PRODUCT='" + product + "'\n"\
            "VERSION='" + version + "'\n"\
            "echo \"Configuring $PRODUCT ($VERSION)...\"\n";
}

std::string OutputScript_Bash::GenerateHeader()
{
    return "#!/bin/bash\n"\
            "#  This program is free software; you can redistribute it and/or modify\n"\
            "#  it under the terms of the GNU Lesser General Public License as published\n"\
            "#  by the Free Software Foundation; either version 2 of the License, or\n"\
            "#  (at your option) version 3.\n\n"\
            "#  This program is distributed in the hope that it will be useful,\n"\
            "#  but WITHOUT ANY WARRANTY; without even the implied warranty of\n"\
            "#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"\
            "#  GNU Lesser General Public License for more details.\n\n"\
            "#  You should have received a copy of the GNU Lesser General Public License\n"\
            "#  along with this program; if not, write to the\n"\
            "#  Free Software Foundation, Inc.,\n"\
            "#  51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.\n\n"\
            "# This configure script was generated by autotools2, see https://github.com/benapetr/autotools2\n\n"\
            "RED=$(tput setaf 1)\n"\
            "WARN=$(tput setaf 3)\n"\
            "GREEN=$(tput setaf 2)\n"\
            "NORMAL=$(tput sgr0)\n";
}
